apiVersion: v1
kind: Service
metadata:  
  name: nodeport-service
spec:
  selector:    
    app: nodeapp
  type: NodePort
  ports:  
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30000
    protocol: TCP